
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - akishitara.akishitara.cronjob-operator
  resources:
  - cronjobopes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - akishitara.akishitara.cronjob-operator
  resources:
  - cronjobopes/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - cronjob
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - cronjob/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - job
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - job/status
  verbs:
  - get
