apiVersion: akishitara.akishitara.cronjob-operator/v1
kind: CronjobOpe
metadata:
  name: cronjobope-sample
spec:
  # Add fields here
  image: ubuntu
  restartPolicy: "Never"
  successfullJobHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: "Allow"
  parallelism: 1
  completions: 1
  backoffLimit: 1
  param1:
    - name: batch1
      schedule: "*/1 * * * *"
      cmd: ["sh", "-c", "date ; echo batch1 ; sleep 10"]
    - name: batch2
      schedule: "*/1 * * * *"
      cmd: ["sh", "-c", "date ; echo batch2 ; sleep 100"]
    - name: batch3
      schedule: "*/1 * * * *"
      cmd: ["sh", "-c", "date ; echo batch3 ; sleep 50"]
    - name: errorbatch
      schedule: "*/2 * * * *"
      cmd: ["sh", "-c", "date ; echo errordesu; echo exception.aaa  ; sleep 30"]
