apiVersion: akishitara.akishitara.cronjob-operator/v1
kind: CronjobOpe
metadata:
  name: cronjobope-sample
spec:
  # Add fields here
  image: ubuntu
  restartPolicy: "Never"
  successfullJobHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: "Allow"
  parallelism: 1
  completions: 1
  backoffLimit: 1
  param1:
    - name: batch1
      schedule: "*/1 * * * *"
      cmd: ["sleep", "100"]
    - name: batch2
      schedule: "*/1 * * * *"
      cmd: ["sleep", "600"]
    - name: batch3
      schedule: "*/1 * * * *"
      cmd: ["sleep", "400"]
